# Generated by Django 5.0.2 on 2025-04-23 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_activation_token'),
        ('schools', '0003_ejercicio_curso_ejercicio_leccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantecurso',
            name='horas_escuchadas',
        ),
        migrations.RemoveField(
            model_name='estudiantecurso',
            name='horas_vistas',
        ),
        migrations.RemoveField(
            model_name='estudiantecurso',
            name='lecciones_vistas',
        ),
        migrations.CreateModel(
            name='EstudianteLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.leccion')),
            ],
        ),
    ]
