# Generated by Django 5.0.2 on 2025-06-13 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_estudiantecurso_horas_escuchadas_and_more'),
        ('schools', '0005_rename_monedas_escuela_basic_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schools.curso'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudianteleccion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudianteleccion',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schools.leccion'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pruebaejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schools.ejercicio'),
        ),
        migrations.AlterField(
            model_name='pruebaejercicio',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.prueba'),
        ),
        migrations.DeleteModel(
            name='EstudianteCurso',
        ),
    ]
