# Generated by Django 5.2.3 on 2025-06-22 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_certificado_curso_alter_certificado_estudiante_and_more'),
        ('schools', '0007_alter_ejercicio_categoria_alter_ejercicio_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.curso'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudianteleccion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estudianteleccion',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.leccion'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pruebaejercicio',
            name='ejercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.ejercicio'),
        ),
        migrations.AlterField(
            model_name='pruebaejercicio',
            name='prueba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.prueba'),
        ),
    ]
