# Generated by Django 5.2.3 on 2025-06-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_certificado_curso_alter_certificado_estudiante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activation_token',
        ),
    ]
