# Generated by Django 5.2.3 on 2025-11-21 02:42

import django.db.models.deletion
from django.db import migrations, models

def forwards_fill_curso(apps, schema_editor):
    EstudianteLeccion = apps.get_model("accounts", "EstudianteLeccion")
    # Leccion vive en la app schools
    Leccion = apps.get_model("schools", "Leccion")

    for el in EstudianteLeccion.objects.select_related("leccion").all():
        if el.leccion_id:
            # asumiendo que Leccion tiene curso_id
            el.curso_id = el.leccion.curso_id
            el.save(update_fields=["curso"])

def reverse_noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usuario_date_joined'),
        ('schools', '0009_alter_ejercicio_pregunta_alter_ejercicio_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteleccion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progresos_lecciones', to='schools.curso'),
        ),
        migrations.AddField(
            model_name='estudianteleccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(forwards_fill_curso, reverse_noop),
    ]
