# Generated by Django 5.2.3 on 2026-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usuario_activation_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='estudianteleccion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
