# Generated by Django 5.2.3 on 2026-06-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_pushtoken_notificacion'),
        ('schools', '0013_recurso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudianteleccion',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AddIndex(
            model_name='estudianteleccion',
            index=models.Index(fields=['estudiante', 'curso'], name='accounts_es_estudia_157a81_idx'),
        ),
        migrations.AddConstraint(
            model_name='estudianteleccion',
            constraint=models.UniqueConstraint(fields=('estudiante', 'leccion'), name='unique_estudianteleccion_estudiante_leccion'),
        ),
    ]
