# Generated by Django 5.2.3 on 2026-06-17 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_estudianteleccion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='next_energy_regen_at',
        ),
    ]
