# Generated by Django 5.2.3 on 2026-07-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_usuario_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
