# Generated by Django 5.2.3 on 2026-07-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_usuario_email_notifications_usuario_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='totp_recovery_codes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
