# Generated by Django 5.2.3 on 2026-07-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_usuario_totp_recovery_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('streak_risk', 'Racha en riesgo'), ('new_lesson', 'Nueva lección'), ('certificate_issued', 'Certificado emitido'), ('test_passed', 'Prueba aprobada'), ('hearts_refilled', 'Vidas recuperadas'), ('access_request', 'Solicitud de acceso'), ('access_request_resolved', 'Solicitud resuelta'), ('promo', 'Promoción'), ('info', 'Informativa')], default='info', max_length=30),
        ),
    ]
