# Generated by Django 5.2.3 on 2026-09-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activation_token',
        ),
    ]
