# Generated by Django 5.2.3 on 2026-09-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_usuario_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='hearts',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='next_heart_regen_at',
        ),
    ]
