# Generated by Django 5.0.2 on 2024-10-19 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('color_hex', models.CharField(default='#545050', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('costo', models.IntegerField(null=True)),
                ('url_image', models.URLField(default='http://placeholder.url', null=True)),
                ('url_icon', models.URLField(default='http://placeholder.url', null=True)),
                ('is_proffesional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('monedas', models.IntegerField(default=0)),
                ('suscripcion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Glosario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('termino', models.CharField(max_length=100, null=True)),
                ('significado', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('opcion_a', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_b', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_c', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_d', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_e', models.CharField(blank=True, max_length=255, null=True)),
                ('opcion_f', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('posicion', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('url_video', models.URLField(default='http://placeholder.url')),
                ('url_audio', models.URLField(default='http://placeholder.url')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.categoria')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.curso')),
            ],
        ),
    ]
