# Generated by Django 5.0.2 on 2025-01-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='contacto',
        ),
    ]
