# Generated by Django 5.0.2 on 2025-02-03 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_remove_escuela_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schools.curso'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='leccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schools.leccion'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schools.categoria'),
        ),
    ]
