# Generated by Django 5.0.2 on 2025-04-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_ejercicio_curso_ejercicio_leccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escuela',
            old_name='suscripcion',
            new_name='basic_access',
        ),
        migrations.AddField(
            model_name='escuela',
            name='professional_access',
            field=models.BooleanField(default=False),
        ),
    ]
