# Generated by Django 5.0.2 on 2025-05-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_rename_suscripcion_escuela_basic_access_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escuela',
            old_name='monedas',
            new_name='basic_key',
        ),
        migrations.AddField(
            model_name='escuela',
            name='professional_key',
            field=models.IntegerField(default=0),
        ),
    ]
