# Generated by Django 5.0.2 on 2025-06-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_rename_monedas_escuela_basic_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
