# Generated by Django 5.2.3 on 2025-06-22 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_curso_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.categoria'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.curso'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='leccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.leccion'),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.categoria'),
        ),
    ]
