# Generated by Django 5.2.3 on 2025-07-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_ejercicio_categoria_alter_ejercicio_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='imagen',
            field=models.URLField(default='http://placeholder.url'),
        ),
    ]
