# Generated by Django 5.2.3 on 2025-09-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_ejercicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='pregunta',
            field=models.TextField(blank=True, default='Pregunta', max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='respuesta',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
