# Generated by Django 5.2.3 on 2026-05-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_rename_is_proffesional_curso_is_profesional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ejercicio',
            options={'ordering': ['id']},
        ),
    ]
