# Generated by Django 5.2.3 on 2026-05-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_alter_curso_options_alter_ejercicio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leccion',
            options={'ordering': ['curso', 'posicion', 'id']},
        ),
        migrations.AddField(
            model_name='leccion',
            name='contenido',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leccion',
            name='duracion_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leccion',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('quiz', 'Quiz'), ('drag', 'Drag & Drop'), ('identify', 'Identificar')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='leccion',
            name='transcripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leccion',
            name='url_pdf',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='schools.curso')),
            ],
            options={
                'ordering': ['curso', 'orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='leccion',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecciones', to='schools.unidad'),
        ),
        migrations.AddConstraint(
            model_name='unidad',
            constraint=models.UniqueConstraint(fields=('curso', 'orden'), name='unique_unidad_orden_por_curso'),
        ),
    ]
