# Generated by Django 5.2.3 on 2026-05-24 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_alter_leccion_options_leccion_contenido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('audio', 'Audio'), ('link', 'Enlace externo')], default='pdf', max_length=20)),
                ('url', models.URLField()),
                ('paginas', models.IntegerField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('requires_owned_course', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.categoria')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='schools.curso')),
                ('leccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos', to='schools.leccion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
