# Generated by Django 5.2.3 on 2026-07-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='explicacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
