# Generated by Django 5.2.3 on 2026-07-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_ejercicio_explicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='basic_seats_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escuela',
            name='basic_seats_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escuela',
            name='professional_seats_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escuela',
            name='professional_seats_used',
            field=models.IntegerField(default=0),
        ),
    ]
