# Generated by Django 5.2.3 on 2026-07-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_leccion_texto_leccionfuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
    ]
