# Generated by Django 5.2.3 on 2026-07-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_backfill_codigo_escuela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='professional_access',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='professional_key',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='professional_seats_max',
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='professional_seats_used',
        ),
    ]
