# Generated by Django 5.2.3 on 2026-09-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_remove_escuela_professional_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='respuestas_correctas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
