# Generated by Django 5.2.3 on 2026-09-13 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_ejercicio_multiple_ejercicio_respuestas_correctas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.IntegerField(choices=[(7, '7 días'), (14, '14 días'), (35, '35 días (1 mes + 5 de regalo)')])),
                ('precio', models.IntegerField()),
                ('precio_referencia', models.IntegerField(blank=True, null=True)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=60)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='schools.curso')),
            ],
            options={
                'ordering': ['curso', 'dias'],
                'unique_together': {('curso', 'dias')},
            },
        ),
    ]
