# Generated by Django 5.2.3 on 2026-09-13 23:00

from django.db import migrations


# Múltiplos que replican el comportamiento previo (costo × llaves): 7→1, 14→2,
# 35→5. Etiqueta especial para el plan mensual.
PLANES = [
    (7, 1, ""),
    (14, 2, ""),
    (35, 5, "1 mes + 5 de regalo"),
]


def backfill(apps, schema_editor):
    Curso = apps.get_model("schools", "Curso")
    PlanCurso = apps.get_model("schools", "PlanCurso")
    for curso in Curso.objects.all():
        costo = int(curso.costo or 0)
        if costo <= 0:
            continue
        for dias, llaves, etiqueta in PLANES:
            PlanCurso.objects.get_or_create(
                curso=curso,
                dias=dias,
                defaults={
                    "precio": costo * llaves,
                    "etiqueta": etiqueta,
                    "activo": True,
                    "orden": dias,
                },
            )


def unbackfill(apps, schema_editor):
    PlanCurso = apps.get_model("schools", "PlanCurso")
    PlanCurso.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_plancurso'),
    ]

    operations = [
        migrations.RunPython(backfill, unbackfill),
    ]
