# Generated by Django 5.2.3 on 2026-09-14 01:36

from django.db import migrations


def guard_planes(apps, schema_editor):
    """Red de seguridad antes de dropear `costo`: todo curso con costo>0 que no
    tenga aún un plan de 7 días recibe uno (valor unitario = costo). Los cursos
    ya backfilleados (0022) no se tocan."""
    Curso = apps.get_model("schools", "Curso")
    PlanCurso = apps.get_model("schools", "PlanCurso")
    for curso in Curso.objects.all():
        costo = int(getattr(curso, "costo", 0) or 0)
        if costo <= 0:
            continue
        PlanCurso.objects.get_or_create(
            curso=curso, dias=7,
            defaults={"precio": costo, "activo": True, "orden": 7},
        )


def noop(apps, schema_editor):
    # No se restaura `costo` (columna eliminada). El precio queda en PlanCurso.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_backfill_plancurso'),
    ]

    operations = [
        # 1) Asegura el plan de 7 días leyendo `costo` (aún existe aquí).
        migrations.RunPython(guard_planes, noop),
        # 2) Elimina la columna deprecada.
        migrations.RemoveField(
            model_name='curso',
            name='costo',
        ),
    ]
