# Generated by Django 5.2.3 on 2026-10-02 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0023_remove_curso_costo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeccionImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('orden', models.IntegerField(default=0)),
                ('pagina', models.IntegerField(blank=True, null=True)),
                ('pie', models.CharField(blank=True, default='', max_length=255)),
                ('alt', models.CharField(blank=True, default='', max_length=500)),
                ('ancho', models.IntegerField(default=0)),
                ('alto', models.IntegerField(default=0)),
                ('origen', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word')], default='pdf', max_length=10)),
                ('mapeo', models.CharField(blank=True, default='', max_length=20)),
                ('hash', models.CharField(blank=True, default='', max_length=64)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='schools.leccion')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
