# Generated by Django 5.2.3 on 2026-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0027_delete_leccionimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='escuela',
            name='basic_access_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
