# Generated by Django 5.2.3 on 2026-08-28 23:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('sales', '0001_initial'), ('sales', '0002_producto_valor_neto_alter_producto_valor_mensual'), ('sales', '0003_remove_producto_is_sub_remove_producto_valor_anual_and_more'), ('sales', '0004_remove_accesskey_producto_accesskey_created_date_and_more'), ('sales', '0005_rename_all_access_producto_basic_access_and_more'), ('sales', '0006_transbanktransaction'), ('sales', '0007_remove_producto_cantidad_producto_cant_basic_key_and_more'), ('sales', '0008_remove_accesskey_is_used'), ('sales', '0009_remove_accesskey_assigned_to_remove_accesskey_curso'), ('sales', '0010_rename_created_date_accesskey_valid_from_and_more'), ('sales', '0011_accesskey_status_alter_accesskey_id_and_more'), ('sales', '0012_alter_transbanktransaction_sale_estudiantecurso'), ('sales', '0013_alter_estudiantecurso_estudiante_id'), ('sales', '0014_alter_estudiantecurso_access_key_id_and_more'), ('sales', '0015_alter_producto_options'), ('sales', '0016_estudiantecurso_unique_estudiantecurso_estudiante_curso'), ('sales', '0017_alter_estudiantecurso_options'), ('sales', '0018_accesskey_origen_alter_accesskey_valid_until'), ('sales', '0019_alter_transbanktransaction_token'), ('sales', '0020_venta_curso_alter_accesskey_origen_and_more'), ('sales', '0021_solicitudacceso'), ('sales', '0022_remove_producto_cant_professional_key_and_more')]

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('schools', '0002_remove_escuela_contacto'),
        ('schools', '0003_ejercicio_curso_ejercicio_leccion_and_more'),
        ('schools', '0005_rename_monedas_escuela_basic_key_and_more'),
        ('schools', '0007_alter_ejercicio_categoria_alter_ejercicio_curso_and_more'),
        ('schools', '0012_alter_leccion_options_leccion_contenido_and_more'),
        ('schools', '0016_leccion_texto_leccionfuente'),
        ('schools', '0017_escuela_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('llave', 'Llave'), ('suscripcion', 'Suscripción')], max_length=20)),
                ('descripcion', models.TextField()),
                ('basic_access', models.BooleanField(default=False)),
                ('valor_neto', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='CLP', max_length=3)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cant_basic_key', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_system', models.CharField(max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('escuela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.escuela')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.curso')),
            ],
        ),
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('origen', models.CharField(choices=[('key', 'Llave temporal'), ('seat', 'Cupo de suscripción'), ('purchase', 'Compra individual')], default='key', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.accesskey')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.curso')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('estudiante_id', 'curso_id'), name='unique_estudiantecurso_estudiante_curso')],
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransbankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(null=True)),
                ('payment_type_code', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('buy_order', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(null=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transbank_transaction', to='sales.venta')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('motivo_rechazo', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.curso')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_acceso', to='schools.escuela')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_acceso', to=settings.AUTH_USER_MODEL)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['escuela', 'estado', '-created_at'], name='sales_solic_escuela_141fbc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'pendiente')), fields=('estudiante', 'curso'), name='unique_solicitud_pendiente_por_curso')],
            },
        ),
    ]
