# Generated by Django 5.0.2 on 2024-10-19 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.TextField(max_length=20)),
                ('valor_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_anual', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.TextField()),
                ('is_sub', models.BooleanField(default=False)),
                ('all_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_system', models.CharField(max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('transbank_token', models.CharField(blank=True, max_length=64, null=True)),
                ('escuela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.escuela')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
