# Generated by Django 5.0.2 on 2025-01-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valor_neto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
