# Generated by Django 5.0.2 on 2025-02-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_producto_is_sub_remove_producto_valor_anual_and_more'),
        ('schools', '0002_remove_escuela_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesskey',
            name='producto',
        ),
        migrations.AddField(
            model_name='accesskey',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='accesskey',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.curso'),
        ),
        migrations.AddField(
            model_name='accesskey',
            name='used_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
