# Generated by Django 5.0.2 on 2025-04-23 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_accesskey_producto_accesskey_created_date_and_more'),
        ('schools', '0003_ejercicio_curso_ejercicio_leccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='all_access',
            new_name='basic_access',
        ),
        migrations.AddField(
            model_name='producto',
            name='professional_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='schools.escuela'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
