# Generated by Django 5.0.2 on 2025-04-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_all_access_producto_basic_access_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransbankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(null=True)),
                ('payment_type_code', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('buy_order', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(null=True)),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transbank_transaction', to='sales.venta')),
            ],
        ),
    ]
