# Generated by Django 5.0.2 on 2025-05-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_transbanktransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='cant_basic_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='cant_professional_key',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
