# Generated by Django 5.0.2 on 2025-05-02 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_producto_cantidad_producto_cant_basic_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesskey',
            name='is_used',
        ),
    ]
