# Generated by Django 5.0.2 on 2025-06-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_accesskey_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesskey',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='accesskey',
            name='curso',
        ),
    ]
