# Generated by Django 5.0.2 on 2025-06-13 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_accesskey_assigned_to_remove_accesskey_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesskey',
            old_name='created_date',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='accesskey',
            old_name='used_date',
            new_name='valid_until',
        ),
    ]
