# Generated by Django 5.0.2 on 2025-06-13 01:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_rename_created_date_accesskey_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('revoked', 'Revoked')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
