# Generated by Django 5.0.2 on 2025-06-13 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_accesskey_status_alter_accesskey_id_and_more'),
        ('schools', '0005_rename_monedas_escuela_basic_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transbanktransaction',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transbank_transaction', to='sales.venta'),
        ),
        migrations.CreateModel(
            name='EstudianteCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sales.accesskey')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schools.curso')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
