# Generated by Django 5.2.3 on 2025-06-22 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_estudiantecurso_estudiante_id'),
        ('schools', '0007_alter_ejercicio_categoria_alter_ejercicio_curso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantecurso',
            name='access_key_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.accesskey'),
        ),
        migrations.AlterField(
            model_name='estudiantecurso',
            name='curso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.curso'),
        ),
        migrations.AlterField(
            model_name='transbanktransaction',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transbank_transaction', to='sales.venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.escuela'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
