# Generated by Django 5.2.3 on 2026-05-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_estudiantecurso_access_key_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id']},
        ),
    ]
