# Generated by Django 5.2.3 on 2026-05-24 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_producto_options'),
        ('schools', '0012_alter_leccion_options_leccion_contenido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='estudiantecurso',
            constraint=models.UniqueConstraint(fields=('estudiante_id', 'curso_id'), name='unique_estudiantecurso_estudiante_curso'),
        ),
    ]
