# Generated by Django 5.2.3 on 2026-06-17 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_estudiantecurso_unique_estudiantecurso_estudiante_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantecurso',
            options={'ordering': ['id']},
        ),
    ]
