# Generated by Django 5.2.3 on 2026-07-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_estudiantecurso_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='origen',
            field=models.CharField(choices=[('key', 'Llave temporal'), ('seat', 'Cupo de suscripción')], default='key', max_length=10),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
