# Generated by Django 5.2.3 on 2026-07-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_accesskey_origen_alter_accesskey_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transbanktransaction',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
