# Generated by Django 5.2.3 on 2026-07-13 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_transbanktransaction_token'),
        ('schools', '0016_leccion_texto_leccionfuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.curso'),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='origen',
            field=models.CharField(choices=[('key', 'Llave temporal'), ('seat', 'Cupo de suscripción'), ('purchase', 'Compra individual')], default='key', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.producto'),
        ),
    ]
