# Generated by Django 5.2.3 on 2026-07-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_solicitudacceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cant_professional_key',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='professional_access',
        ),
    ]
