# Generated by Django 5.2.3 on 2026-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cant_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='duracion_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
