# Generated by Django 5.2.3 on 2026-10-06 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_producto_cupos_duracion'),
        ('schools', '0028_escuela_basic_access_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesskey',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos', to='schools.escuela'),
        ),
        migrations.AddField(
            model_name='accesskey',
            name='llaves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
